apiVersion: v1
kind: Pod
metadata:
  name: lbdsr0a
spec:
  containers:
  - image: snpsuen/ebpf-xdp:v02
    name: lbdsr0a
    ports:
    - containerPort: 80
    command:
    - sleep
    - infinity
    securityContext:
      privileged: true
  nodeSelector:
    loadbalancer: dsr
---
apiVersion: v1
kind: Pod
metadata:
  name: backend0x
spec:
  containers:
  - image: nginxdemos/hello:plain-text
    name: backend0x
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
  nodeSelector:
    loadbalancer: dsr
---
apiVersion: v1
kind: Pod
metadata:
  name: backend0y
spec:
  containers:
  - image: nginxdemos/hello:plain-text
    name: backend0y
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
  nodeSelector:
    loadbalancer: dsr
