apiVersion: v1
kind: Pod
metadata:
  name: lbdsr01
spec:
  containers:
  - image: snpsuen/ebpf-xdp:v02
    name: lbdsr01
    ports:
    - containerPort: 80
    command:
    - sleep
    - infinity
    securityContext:
      privileged: true
